#!/bin/sh
set -e

### BEGIN INIT INFO
# Provides:           tmuxstatus
# Required-Start:     $remote_fs $syslog
# Required-Stop:      $remote_fs $syslog
# Default-Start:      2 3 4 5
# Default-Stop:       0 1 6
### END INIT INFO

PATH="/sbin:/usr/sbin:/bin:/usr/bin"
NAME="tmuxstatusd"
DAEMON="/usr/bin/tmuxstatusd"
PIDFILE="/var/run/$NAME.pid"
LOGFILE="/var/log/$NAME.log"

TRUE=1
FALSE=0

. /lib/lsb/init-functions

start() {
  start-stop-daemon \
    --start \
    --background \
    --no-close \
    --pidfile "$PIDFILE" \
    --make-pidfile \
    --exec "$DAEMON" \
    >> "$LOGFILE" 2>&1

  log_end_msg $?
}

stop() {
  start-stop-daemon \
    --stop \
    --pidfile "$PIDFILE" \
    --retry 10 \
    || return 1

  retval="$?"

  rm -f "$PIDFILE"

  log_end_msg "$retval"
}

check_is_running() {
  if [ ! -f "$PIDFILE" ]; then
    echo "$FALSE"
    return
  fi

  pid="$(cat "$PIDFILE" 2>/dev/null)"

  if [ -n "$pid" ]; then
    echo $TRUE
  else
    echo $FALSE
  fi
}

case "$1" in
  start)
    log_begin_msg "Starting $NAME"
    is_running="$(check_is_running)"
    [ "$(check_is_running)" = "$FALSE" ] && start
    ;;

  stop)
    log_begin_msg "Stopping $NAME"
    [ "$(check_is_running)" = "$TRUE" ] && stop
    ;;

  restart)
    log_begin_msg "Restarting $NAME"
    [ "$(check_is_running)" = "$TRUE" ] && stop
    [ "$(check_is_running)" = "$FALSE" ] && start
    ;;

  status)
    status_of_proc "$DAEMON" "$NAME" && exit 0 || exit $?
    ;;

  *)
    echo "Usage: service $NAME {start|stop|restart|status}"
    exit 1
    ;;
esac


exit 0
